### ISSUE TITLE
playerID deprecated warning iOS 8

### ISSUE THREAD

**Issue by GunZi200** [leecrossley/cordova-plugin-game-center#24]
/hello/platforms/ios/HelloWorld/Plugins/uk.co.ilee.gamecenter/GameCenter.m:250:51: 'playerID' is deprecated: first deprecated in iOS 8.0 - use player

Is there a fix for this?

**Comment by leecrossley** [comment]
This is a deprecation message, not an error. Any deprecations will be addressed in the next release
