### ISSUE TITLE
Achievement message displayed wrongly on iOS7 

### ISSUE THREAD

**Issue by ruudruud** [leecrossley/cordova-plugin-game-center#26]
Thank you Lee for the quick fix of #25.

I have found another related issue with posting an achievement. When you post an achievement on iOS7 the "Achievement completed" message is also shown when the percentage is not 100%. My app currently shows an endless loop of completed messages, when in reality the achievement is not completed yet.

I suggest to only show this message when the given percentage is 100.

**Comment by donkeyspaceman** [comment]
I am also having this issue.
