### ISSUE TITLE
GameCenter plugin and AngularJS + Ionic

### ISSUE THREAD

**Issue by mariohmol** [leecrossley/cordova-plugin-game-center#29]
Hy there,

could not make it work on AngularJS and Ionic.

I'm always getting this message: 

* D/PluginManager(2836): exec() call to unknown plugin: GameCenter

Installed using cordova plugin add, and included the call on read for ionic

```
app.run(function($rootScope, $ionicLoading,$ionicPopup,$ionicPlatform) {
	var failureLoginCallback = function (user) {
		console.log("ERRROOOO failureCallback");
	    console.log(user);
	};
		
	var successLoginCallback = function (user) {
		console.log("SUCESSO LOGIN");
	    alert(user.alias);
	    // user.alias, user.playerID, user.displayName
	};

	$ionicPlatform.ready(function() {
		
		gamecenter.auth(successLoginCallback, failureLoginCallback);
		
	});
```

Any ideas?

**Comment by leecrossley** [comment]
I've just run this code and it works with a fresh install. It sounds like the plugin is not installed properly (perhaps try it again).

If you can create a demo project that reproduces this issue I will reopen. Thanks.

**Comment by mariohmol** [comment]
I had to copy GameCenter.m and GameCenter.h manually to plugins/uk.co.ilee.gamecenter/src/ios/, cause add and remove plugin were not doing.

**Comment by leecrossley** [comment]
Perhaps you had filesystem permissions issues or an issue with your setup. Glad it's at least working.
