### ISSUE TITLE
How to auth?

### ISSUE THREAD

**Issue by tryagains** [leecrossley/cordova-plugin-game-center#30]
var successCallback = function (user) {
    alert(user.alias);
    // user.alias, user.playerID, user.displayName
};

gamecenter.auth(successCallback, failureCallback);

Do we uncomment //user.alias, user.playerID, user.displayName?
And do we replace the playerID/displayName/alias with something?

**Comment by leecrossley** [comment]
If your `successCallback` function is called, it means that auth has been successful. The commented properties are there to illustrate what values are available but you do not need to use these.
